### ISSUE TITLE
Not working with webpack-dev-server

### ISSUE THREAD

**Issue by vlio20** [hyunchulkwak/webpack-simple-progress-plugin#1] opened 2017-05-25 11:20 UTC
seems like this plugin not working with webpack-dev-server

**Comment by hyunchulkwak** [comment] 2017-06-01 07:34
@vlio20 could you explain some specific configs you are using? I found it's working okay with the latest version of webpack and webpack-dev-server, which is like below.

```
"dependencies": {
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-simple-progress-plugin": "^0.0.1"
}
```

**Comment by vlio20** [comment] 2017-06-01 10:03
Here is my full configuration:  
```
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = () => {

  return {
    stats: {
      assets: true,
      cached: false,
      cachedAssets: false,
      children: false,
      chunks: true,
      chunkModules: false,
      chunkOrigins: false,
      colors: true,
      depth: false,
      entrypoints: false,
      errors: true,
      errorDetails: true,
      maxModules: 0,
      modules: false,
      performance: false,
      providedExports: false,
      publicPath: true,
      reasons: false,
      source: false,
      timings: true,
      usedExports: false,
      version: true,
      warnings: false
    },
    performance: {
      hints: false
    },
    entry: {
      app: './src/app/app.modules.ts',
      vendor: './src/app/vendor/vendor.ts',
      mock: './src/mock/states.ts'
    },
    output: {
      path: require('path').resolve('./static'),
      filename: '[name].js',
      publicPath: '/erapp/static/'
    },
    resolve: {
      extensions: ['.js', '.ts', '.less', '.css', '.html'],
      alias: {
        'jquery': require.resolve('jquery')
      }
    },
    devtool: 'source-map',
    module: {
      rules: [
        {
          test: /\.ts?$/,
          use: ['ts-loader']
        },
        {
          test: /\.css$/,
          loader: ExtractTextPlugin.extract(
            {
              fallbackLoader: 'style-loader',
              loader: 'css-loader'
            })
        },
        {
          test: /\.less$/,
          loader: ExtractTextPlugin.extract(
            {
              fallbackLoader: 'style-loader',
              loader: 'css-loader!less-loader'
            })
        },
        {
          test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
          use: [
            'file-loader?name=fonts/[name].[ext]?[hash]'
          ]
        },
        {
          test: /\.(gif|png(2)?)(\?[a-z0-9=&.]+)?$/,
          use: [
            'file-loader?name=images/[name].[ext]?[hash]'
          ]
        },
        {
          test: /\.html$/,
          use: [
            'html-loader'
          ]
        },
        {
          test: /\/leonardo.js/,
          use: [
            'script-loader'
          ]
        }
      ]
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new webpack.optimize.CommonsChunkPlugin({
        names: ['vendor', 'manifest']
      }),
      new webpack.ProvidePlugin({
        moment: 'moment',
        Highcharts: 'highcharts',
        'jQuery': 'jquery',
        '$': 'jquery',
        'window.jQuery': 'jquery'
      }),
      new ExtractTextPlugin('[name].css'),
      new HtmlWebpackPlugin({
        filename: 'index.dev.html',
        hash: false,
        template: './src/app/index.tpl',
        chunks: ['manifest', 'vendor', 'mock', 'app'],
        env: 'dev'
      })
    ],
    devServer: {
      port: 5151,
      inline: true,
      stats: 'errors-only',
      open: true,
      publicPath: '/erapp/site/',
      historyApiFallback: {
        index: '/erapp/site/index.dev.html'
      },
      proxy: {
        '/erapp/static': {
          target: 'http://localhost:5151',
          pathRewrite: {'static': 'site'}
        }
      }
    }
  }
};
```

Adding the plugin to this configuration just doesn't change the output when webpack is building - both in startup nor while in hot module is running

**Comment by hyunchulkwak** [comment] 2017-06-01 14:06
@vlio20 thanks, I should look into it

**Comment by hyunchulkwak** [comment] 2017-06-01 14:47
@vlio20 Here's a repo for mimicking your configs. I still see the progress bar's working, Please let me know some clues. Thanks.

https://github.com/hyunchulkwak/temporary-webpack-test

**Comment by vlio20** [comment] 2017-06-01 14:52
How are you running the dev server? With what command?

**Comment by hyunchulkwak** [comment] 2017-06-01 14:57
@vlio20 I globally installed it so just run it by typing webpack-dev-server

**Comment by hyunchulkwak** [comment] 2017-06-07 14:53
@vlio20 please let me know if there's any progress.. thanks a lot!

**Comment by hyunchulkwak** [comment] 2017-08-20 14:56
close this since I can't reproduce and haven't got further responses. thanks.

**Closed as completed by hyunchulkwak** 2017-08-20 14:56 UTC
